### ISSUE TITLE
NameError has different error message from MRI

### ISSUE THREAD

**Issue by myronmarston** [rubinius/rubinius#503]
Compare these:

<pre>
$  ruby --version
ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-darwin10.4.0]
$ irb
> foo
NameError: undefined local variable or method `foo' for #<Object:0x1001c92a0>
        from (irb):1
</pre>

<pre>
$ ruby --version
rubinius 1.1.0 (1.8.7 a38ea379 2010-09-23 JI) [x86_64-apple-darwin10.4.0]
$ irb
> foo
NameError: no method or variable 'foo' on an instance of Object.
</pre>

I had some code that was using a regex to parse out the name of the undefined method or variable (`foo`, in this case).  It worked fine on MRI 1.8.6, 1.8.7, 1.9.1, 1.9.2, REE and JRuby.  It failed on rubinius since it uses a different error message.  Obviously, this really isn't a good idea--I shouldn't be relying upon the wording of an error message.  I've fixed it to call `NameError#name`.  I didn't realize this method existed before.  Still, for rubinius to have the best compatibility with other ruby interpreters, it probably shouldn't be changing the standard wording of exceptions, unless there is a strong, specific reason to do so.
