### ISSUE TITLE
rb_io_t compilation issues (can't compile kdtree gem)

### ISSUE THREAD

**Issue by ghazel** [rubinius/rubinius#830]
This compilation works fine on MRI 1.8.7

$ gem install kdtree
Fetching: kdtree-0.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing kdtree:
        ERROR: Failed to build gem native extension.

```
    /home/user/rubinius/bin/rbx extconf.rb
```

creating Makefile

make
gcc -I. -I/home/user/rubinius/vm/capi/include -I/home/user/rubinius/vm/capi/include -I.  -fPIC -ggdb3 -O2 -fPIC  -c kdtree.c
kdtree.c:66: warning: 'struct rb_io_t' declared inside parameter list
kdtree.c:66: warning: its scope is only this definition or declaration, which is probably not what you want
kdtree.c: In function 'read_all':
kdtree.c:69: error: dereferencing pointer to incomplete type
kdtree.c: In function 'kdtree_initialize':
kdtree.c:132: error: invalid type argument of '->'
kdtree.c:133: warning: passing argument 1 of 'rb_io_check_readable' from incompatible pointer type
kdtree.c:137: warning: passing argument 1 of 'read_all' from incompatible pointer type
kdtree.c:143: warning: passing argument 1 of 'read_all' from incompatible pointer type
kdtree.c:146: warning: passing argument 1 of 'read_all' from incompatible pointer type
make: **\* [kdtree.o] Error 1

Gem files will remain installed in /home/user/rubinius/gems/1.8/gems/kdtree-0.1 for inspection.
Results logged to /home/user/rubinius/gems/1.8/gems/kdtree-0.1/ext/gem_make.out
