### ISSUE TITLE
Gem error after Rubinius 3.3 install

### ISSUE THREAD

**Issue by ljulliar** [rubinius/rubinius#3557]
After successfully installing rubinius 3.3 through docker on Ubuntu 14.04 64bits I cannot make the gem command work properly. Any clue ?

```
$ docker pull rubinius/rubinius
....
Status: Downloaded newer image for rubinius/rubinius:latest
$ docker run -it rubinius/rubinius bash
root@32ca2f655d15:/# ruby -v
rubinius 3.3 (2.2.0 f9a03f81 2016-01-08 3.4.2 JI) [x86_64-linux-gnu]
root@32ca2f655d15:/# gem list
An exception occurred running /opt/rubinius/3.3/library/bin/gem.rb

Missing or uninitialized constant: Psych::Parser (NameError)
```

**Comment by medols** [comment]
Tried installing libyaml-dev and libssl-dev but I cannot make the gem command work either.

```shell
$ docker run -it rubinius/rubinius
root@5d9ca5ef926c:/# ruby -v
rubinius 3.9 (2.2.0 e265a22a 2016-01-16 3.4.2 JI) [x86_64-linux-gnu]
root@5d9ca5ef926c:/# apt-get update
root@5d9ca5ef926c:/# apt-get install libyaml-dev libssl-dev
root@5d9ca5ef926c:/# gem list

*** LOCAL GEMS ***

bundler (1.11.2)
(...)
rubysl-zlib (2.0.1)

root@5d9ca5ef926c:/# gem install rubinius-actor
ERROR:  Loading command: install (LoadError::InvalidExtensionError)
	Could not open library /opt/rubinius/3.9/gems/gems/rubysl-openssl-2.8.0/lib/openssl/openssl.so - /opt/rubinius/3.9/gems/gems/rubysl-openssl-2.8.0/lib/openssl/openssl.so: symbol CRYPTO_memcmp, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' on nil:NilClass.
root@5d9ca5ef926c:/# 
```

**Comment by brixen** [comment]
@medols it's this nasty bit here:

```
Could not open library /opt/rubinius/3.9/gems/gems/rubysl-openssl-2.8.0/lib/openssl/openssl.so - /opt/rubinius/3.9/gems/gems/rubysl-openssl-2.8.0/lib/openssl/openssl.so: symbol CRYPTO_memcmp, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference
```

The basic problem is that the OpenSSL ABI is very unstable. We won't be able to share binaries and trying to statically link runs into all sorts of other problems.

@ljulliar you'll basically run into the same issue. Installing libyaml works (because the ABI is pretty stable).

We're in the process of setting up separate builds for 12.04, 14.04, and 15.10 (which will transition to 16.04 when that is released). For now, I should be able to put up a 12.04 image (checking on that).

I'm going to remove uploading the 14.04 and 15.10 binaries until we can build them separately.

**Comment by medols** [comment]
Solved with the docker 12.04 image from rubinius/docker, thank you.

**Comment by brixen** [comment]
@medols good to hear! Would you use a 15.10 (or 16.04) image if available?

**Comment by medols** [comment]
We can work well with 12.04 in the meantime, then push to the latest stable when available, 
Thank you.

**Comment by medols** [comment]
@brixen the rubinius/docker has a very small footprint, good work !
[This link](https://hub.docker.com/r/rubinius/rubinius/builds) from [rubinius.com](http://rubinius.com)
returns 404 now.

**Comment by brixen** [comment]
@medols thanks for pinging me, I had the changes local and forgot to push them, doh! If you refresh, it should be correct now.
