### ISSUE TITLE
git trunk does not compile on OS X 10.6.2

### ISSUE THREAD

**Issue by keltia** [rubinius/rubinius#191]
Running with ruby 1.8.7 from macports, trying to compile rubinius from trunk does not compile:

CC vm/llvm/autotypes.cpp
gcc -Ivm/external_libs/libtommath -Ivm/external_libs/libgdtoa -Ivm/external_libs/onig -Ivm/external_libs/libffi/include -Ivm/external_libs/libltdl -Ivm/external_libs/libev -Ivm/test/cxxtest -Ivm -I. -I/usr/local/include -I/opt/local/include -Ivm/external_libs/udis86 -pipe -Wall -Wno-deprecated -mdynamic-no-pic -DENABLE_LLVM -DHAS_EXECINFO -ggdb3 -O2 -Werror -DRBX_PROFILER -Ivm/external_libs/llvm/include -I/Volumes/Users/roberto/Build/GIT/rubinius/vm/external_libs/llvm/Release/include -D_DEBUG -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -fno-common -c -o vm/llvm/autotypes.o vm/llvm/autotypes.cpp 2>&1
In file included from vm/llvm/autotypes.cpp:18:
vm/llvm/types.cpp.gen: In function ‘llvm::Module\* autogen_types::makeLLVMModuleContents(llvm::Module*)’:
vm/llvm/types.cpp.gen:13: error: ‘getGlobalContext’ was not declared in this scope
rake aborted!
Command failed with status (1): [gcc -Ivm/external_libs/libtommath -Ivm/ext...]

(See full trace by running task with --trace)
