### ISSUE TITLE
Compilation failure on Ubuntu 15.10 64-bit for 3.19

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3632]
## Problem
Compilation of 3.19 fails during linking step (LD vm/vm). Complains about an undefined reference to llvm::sys::getDefaultTargetTriple() in vm/llvm/artifacts/disassembler.cpp.o: 'JITDisassembler'.

There were other issues on this topic but the problem appeared to be due to having multiple LLVM versions installed (e.g 3.5 and 3.6). Since this is a fresh install I know that only clang 3.5 and llvm 3.5 were installed so there should not be any version conflicts.

## How to Reproduce
Install Ubuntu 15.10 64-bit from CD-ROM.
sudo apt-get update
sudo apt-get install git libedit-dev llvm-3.5 clang-3.5 ruby
ruby -S gem install bundler
clone rubinius
bundle install # in rubinius
./configure --cc `which clang-3.5` --cxx `which clang++-3.5` --llvm-path /usr/lib/llvm-3.5 --llvm-config `which llvm-config-3.5`

## Configuration Details

* Output of `rbx -v`:
didn't finish building

* Output of `uname -a`:
Linux ubuntu 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

* Distribution name (in case of Linux/BSD):
Ubuntu

* Contents of `config.rb` (as a Gist link):
https://gist.github.com/chuckremes/5048fa4eda611bd32cb1

* Contents of `configure.log` (as a Gist link):
https://gist.github.com/chuckremes/5048fa4eda611bd32cb1

## Stack Trace

https://gist.github.com/chuckremes/5048fa4eda611bd32cb1

**Comment by brixen** [comment]
Rubinius master HEAD should build with LLVM 3.6+. Please open a new issue if you hit a problem building with 3.6+.
