### ISSUE TITLE
Compilation issues on x86_64

### ISSUE THREAD

**Issue by mernen** [rubinius/rubinius#10]
When trying to compile on my Linux box (Ubuntu 9.04 x86_64, GCC 4.3.3), I get the following errors:

```
vm/builtin/object.cpp: In member function ‘rubinius::hashval rubinius::Object::hash(rubinius::VM*)’:
vm/builtin/object.cpp:237: error: cast from ‘rubinius::Object*’ to ‘uint32_t’ loses precision

cc1plus: warnings being treated as errors
vm/builtin/string.cpp: In function ‘unsigned int rubinius::finish_hash(unsigned int)’:
vm/builtin/string.cpp:140: error: right shift count >= width of type
```

Ad-hoc patches:

```
diff --git i/vm/builtin/object.cpp w/vm/builtin/object.cpp
index f5927cf..11d3e56 100644
--- i/vm/builtin/object.cpp
+++ w/vm/builtin/object.cpp
@@ -234,7 +234,7 @@ namespace rubinius {
   hashval Object::hash(STATE) {
     if(!reference_p()) {
       // See http://burtleburtle.net/bob/hash/integer.html
-      uint32_t a = (uint32_t)this;
+      uint32_t a = (uint32_t)(unsigned long)this;
       a = (a+0x7ed55d16) + (a<<12);
       a = (a^0xc761c23c) ^ (a>>19);
       a = (a+0x165667b1) + (a<<5);

diff --git i/vm/builtin/string.cpp w/vm/builtin/string.cpp
index 570044e..b1f32cc 100644
--- i/vm/builtin/string.cpp
+++ w/vm/builtin/string.cpp
@@ -137,7 +137,7 @@ namespace rubinius {
   }

   static inline unsigned int finish_hash(unsigned int hv) {
-    return (hv>>FIXNUM_WIDTH) ^ (hv & FIXNUM_MAX);
+    return (hv >> (FIXNUM_WIDTH < sizeof(hv) * 8) ? FIXNUM_WIDTH : 0) ^ (hv & F
   }

   hashval String::hash_str(const char *bp) {
```
