### ISSUE TITLE
openssl version issue

### ISSUE THREAD

**Issue by dustalov** [rubinius/rubinius#228]
Rubinius won't to build on OpenSSL v1.0.0-fips-beta4:
    Building Melbourne for Rubinius
    make
    gcc -I. -I. -I/home/eveel/Work/rubinius/vm/capi -I. -DRUBY_EXTCONF_H=\"extconf.h\"  -ggdb3 -O2 -fPIC  -c ossl_pkcs7.c
    ossl_pkcs7.c:573: error: expected '=', ',', ';', 'asm' or '**attribute**' before '_' token
    ossl_pkcs7.c: In function 'ossl_pkcs7_set_certificates':
    ossl_pkcs7.c:611: warning: assignment makes pointer from integer without a cast
    ossl_pkcs7.c: In function 'ossl_pkcs7_get_certificates':
    ossl_pkcs7.c:625: warning: passing argument 1 of 'ossl_x509_sk2ary' makes pointer from integer without a cast
    ossl.h:122: note: expected 'struct stack_st_X509 *' but argument is of type 'int'
    ossl_pkcs7.c: In function 'ossl_pkcs7_set_crls':
    ossl_pkcs7.c:655: warning: assignment makes pointer from integer without a cast
    ossl_pkcs7.c: In function 'ossl_pkcs7_get_crls':
    ossl_pkcs7.c:669: warning: passing argument 1 of 'ossl_x509crl_sk2ary' makes pointer from integer without a cast
    ossl.h:123: note: expected 'struct stack_st_X509_CRL *' but argument is of type 'int'
    make: *_\* [ossl_pkcs7.o] Error 1
    rake aborted!
    Command failed with status (2): [make...]
Please, provide a ./configure option to define the openssl prefix directory, or use the latest OpenSSL version.
