### ISSUE TITLE
Rubinius fails to compile with openssl 1.1.1

### ISSUE THREAD

**Issue by eregon** [rubinius/rubinius#3820]
1. What command did you run?

  I ran `ruby-install rbx`

2. What behavior did you expect?

  I expected it compiles.

3. What behavior did you get instead?

  I observed that compilation failed with OpenSSL 1.1.1b:
https://gist.github.com/eregon/68ca53eb47afd8d3923cc79d9f276b40
Extract:
```
compiling ossl_pkcs12.c
In file included from ossl_pkcs12.c:5:
In file included from ./ossl.h:57:
/usr/include/openssl/asn1_mac.h:10:2: error: "This file is obsolete; please update your software."
#error "This file is obsolete; please update your software."
 ^
In file included from ossl_pkcs12.c:5:
In file included from ./ossl.h:221:
./openssl_missing.h:78:31: error: too many arguments provided to function-like macro invocation
EVP_MD_CTX *EVP_MD_CTX_create(void);
```

4. What version of Rubinius?

4.5

5. What version of operating system?

  Output of `uname -a`:
`Linux localhost.localdomain 5.0.17-200.fc29.x86_64 #1 SMP Mon May 20 15:39:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

7. How did you build your version of Rubinius?

  - [x] I used ruby-install.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by eregon** [comment]
A workaround is to:
```
sudo dnf remove openssl-devel && sudo dnf install compat-openssl10-devel
ruby-install --no-install-deps rbx
sudo dnf remove  compat-openssl10-devel && sudo dnf install openssl-devel
```
But it's obviously not ideal to have to use the compatibility devel package.

From https://www.openssl.org/policies/releasestrat.html:
> OpenSSL 1.0.2 will be supported until 2019-12-31 (LTS).

**Comment by brixen** [comment]
I'm assuming the fix to this is updating the openssl C-ext.

**Comment by eregon** [comment]
> I'm assuming the fix to this is updating the openssl C-ext.

Yes indeed, the C extension of MRI 2.4+ supports OpenSSL 1.1+.

**Comment by brixen** [comment]
Should be fixed.
