### ISSUE TITLE
Failed to install v3.15 on CentOS 7

### ISSUE THREAD

**Issue by bianjp** [rubinius/rubinius#3622]
## Problem

I installed v3.14 successfully several days ago, but when I want to upgrade it to v3.15, `rake install` failed with the following errors:

```
2: CXX vm/accessor_primitives.cpp
In file included from /usr/include/c++/4.8.2/tuple:35:0,
                 from /home/ln/rubinius/vm/builtin/code_db.hpp:8,
                 from vm/gen/includes.hpp:70,
                 from vm/accessor_primitives.cpp:4:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from vm/gen/includes.hpp:70:0,
                 from vm/accessor_primitives.cpp:4:
/home/ln/rubinius/vm/builtin/code_db.hpp:13:11: error: ‘tuple’ in namespace ‘std’ does not name a type
   typedef std::tuple<void*, size_t, size_t> CodeDBIndex;
           ^
/home/ln/rubinius/vm/builtin/code_db.hpp:14:42: error: ‘CodeDBIndex’ was not declared in this scope
   typedef std_unordered_map<std::string, CodeDBIndex> CodeDBMap;
                                          ^
/home/ln/rubinius/vm/builtin/code_db.hpp:14:53: error: template argument 2 is invalid
   typedef std_unordered_map<std::string, CodeDBIndex> CodeDBMap;
                                                     ^
/home/ln/rubinius/vm/builtin/code_db.hpp:14:53: error: template argument 5 is invalid
/home/ln/rubinius/vm/builtin/code_db.hpp:14:64: error: invalid type in declaration before ‘;’ token
   typedef std_unordered_map<std::string, CodeDBIndex> CodeDBMap;
```

## How to Reproduce

On CentOS 7.2, execute the following commands:

```bash
# Dependencies
sudo yum group install -y development
sudo yum install -y epel-release
sudo yum install -y ruby-devel readline-devel zlib-devel openssl-devel libedit-devel llvm-static git
gem install bundler rake
sudo yum update

# Build and install v3.15
git clone git://github.com/rubinius/rubinius.git
cd rubinius
git checkout v3.15
bundle install
./configure --prefix=~/.rbx
rake install
```

## Configuration Details

* Output of `rbx -v`: `rubinius 3.14 (2.2.2 a7ba16db 2016-01-28 3.4.2 JI) [x86_64-linux-gnu]`
* Output of `uname -a`: `Linux walkworld.tv 4.4.0-x86_64-linode63 #2 SMP Tue Jan 19 12:43:53 EST 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Distribution name (in case of Linux/BSD): CentOS
* Contents of `config.rb`: [https://gist.github.com/bianjp/1da44c3c903be4b6419f#file-config-rb]()
* Contents of `configure.log`: [https://gist.github.com/bianjp/1da44c3c903be4b6419f#file-configure-log]()

## Stack Trace

Full output of `rake install --trace`: [https://gist.github.com/bianjp/1da44c3c903be4b6419f#file-stack-trace-log]()

**Comment by YorickPeterse** [comment]
Is it possible to build with LLVM 3.5? Looking at [./configure](https://github.com/rubinius/rubinius/blob/333e3d7aba6bb88d954701e50f6af745b6749030/configure#L670) we enable C++11 mode only when LLVM is >= 3.5.

**Comment by bianjp** [comment]
The latest version of LLVM in [EPEL](https://fedoraproject.org/wiki/EPEL) repo is 3.4.2.

If LLVM >= 3.5 is required, then I have to install it manually.

**Comment by jemc** [comment]
@YorickPeterse - looking through the commit history, it looks like this was only predicated on LLVM 3.5 because LLVM 3.5 needed it, not because it was harmful for LLVM < 3.5.

It looks like the latest CodeDB changes assume C++11 support is present, so let's just move [that line](https://github.com/rubinius/rubinius/blob/333e3d7aba6bb88d954701e50f6af745b6749030/configure#L670) out of the conditional.

**Comment by YorickPeterse** [comment]
@jemc Commit 3bddf4ae mentions something about not applying this to everything (Gems in particular). I'm not sure if always enabling this will break anything. If we can enable it just for the VM code we should be good to go.

**Comment by jemc** [comment]
@YorickPeterse - yes, I saw the commit (and ones further back) when looking at the history.  Look at the diff for that commit - it's already inside the conditional there.  And the diff is changing it from adding it to `system_cxxflags` to adding it to `llvm_cxxflags`.  That's what is meant by the comment about applying it only to VM code and not gems.

**Comment by YorickPeterse** [comment]
@jemc Ah, in that case we can probably just move it outside of the LLVM version guard.

**Comment by jemc** [comment]
@bianjp - Please confirm that the issue is now resolved, and reopen if necessary.

**Comment by bianjp** [comment]
Thanks. Installation is now successful, but after installation any ruby command (like `ruby -v`) failed with the following error:

```
Unable to load the bytecode compiler.

Unable to load the bytecode compiler (LoadError)

Backtrace:

  Rubinius::CodeLoader.load_compiler at core/code_loader.rb:581
      Rubinius::Loader#load_compiler at core/loader.rb:577
               Rubinius::Loader#main at core/loader.rb:855

Caused by: /home/ln/.rbx/runtime/gems/rubinius-ast-2.4.0/lib/rubinius/code/ast.rbc (Rubinius::InvalidRBC)

  Rubinius::CodeLoader#load_compiled_file at core/code_loader.rb:665
        Rubinius::CodeLoader#load_file at core/code_loader.rb:613
          Rubinius::CodeLoader#require at core/code_loader.rb:128
  Rubinius::CodeLoader#require_compiled at core/code_loader.rb:474
  Rubinius::CodeLoader.require_compiled at core/code_loader.rb:586
  { } in Rubinius::CodeLoader.load_compiler at core/code_loader.rb:578
            Rubinius::ToolSets.create at .rbx/runtime/gems/rubinius-toolset-3.0
                                         /lib/rubinius/code/toolset.rbc:21
    Rubinius::CodeLoader.load_compiler at core/code_loader.rb:574
        Rubinius::Loader#load_compiler at core/loader.rb:577
                 Rubinius::Loader#main at core/loader.rb:855
```

**Comment by brixen** [comment]
@bianjp is there a Docker base layer or Vagrant box you could point me to that I could use to repro your issue?

**Comment by bianjp** [comment]
@brixen 
Sorry, I am not familiar with Docker or Vagrant. But running the following commands on a fresh CentOS 7 should be enough.

```
# Dependencies
sudo yum group install -y development
sudo yum install -y epel-release
sudo yum install -y ruby ruby-devel readline-devel zlib-devel openssl-devel libedit-devel llvm-static git
sudo yum update -y
gem install bundler rake

# Build and install
git clone git://github.com/rubinius/rubinius.git
cd rubinius
git checkout master # change as needed
bundle install
./configure --prefix=~/.rbx
rake install

export PATH=~/.rbx/gems/bin/:~/.rbx/bin/:$PATH
```

**Comment by YorickPeterse** [comment]
@bianjp Make sure that if `~/.rbx` already exists it's empty. I've seen this error before sometimes and removing any existing bytecode files usually solves it.

**Comment by bianjp** [comment]
@YorickPeterse You are right. Delete `~/.rbx` and reinstall solved the problem.
Thanks!
