### ISSUE TITLE
gem install em-http-request fails

### ISSUE THREAD

**Issue by rb2k** [rubinius/rubinius#201]
I am not really sure where to put this, but since it works on 1.8 and 1.9.1, I guess this might belong here :)

```
$ gem install em-http-request
Building native extensions.  This could take a while...
ERROR:  Error installing em-http-request:
    ERROR: Failed to build gem native extension.

/Users/mseeger/.rvm/rubies/rbx-1.0.0-rc2/bin/rbx extconf.rb
checking for rb_thread_blocking_region()... no
checking for rb_str_set_len()... no
checking for sys/select.h... yes
checking for poll.h... yes
checking for sys/epoll.h... no
checking for sys/event.h... yes
checking for sys/queue.h... yes
checking for port.h... no
checking for openssl/ssl.h... yes
checking for sysctlbyname() in sys/param.h,sys/sysctl.h... yes
creating Makefile

make
gcc -I. -I. -I/Users/mseeger/.rvm/rubies/rbx-1.0.0-rc2/include -I. -DRUBY_VERSION_CODE=187 -DHAVE_SYS_SELECT_H -DEV_USE_SELECT -DHAVE_POLL_H -DEV_USE_POLL -DHAVE_SYS_EVENT_H -DHAVE_SYS_QUEUE_H -DEV_USE_KQUEUE -DHAVE_OPENSSL_SSL_H -DHAVE_OPENSSL_SSL_H -DHAVE_SYSCTLBYNAME -DHAVE_SYSCTLBYNAME  -ggdb3 -O2  -c em_buffer.c
em_buffer.c: In function ‘Em_Buffer_read_from’:
em_buffer.c:294: error: ‘OpenFile’ undeclared (first use in this function)
em_buffer.c:294: error: (Each undeclared identifier is reported only once
em_buffer.c:294: error: for each function it appears in.)
em_buffer.c:294: error: ‘fptr’ undeclared (first use in this function)
em_buffer.c: In function ‘Em_Buffer_write_to’:
em_buffer.c:317: error: ‘OpenFile’ undeclared (first use in this function)
em_buffer.c:317: error: ‘fptr’ undeclared (first use in this function)
make: *** [em_buffer.o] Error 1
```

p.s. eventmachine itself works!
