### ISSUE TITLE
autoload chaining broken in 2.5.8 cf. MRI 2.1.7

### ISSUE THREAD

**Issue by mwpastore** [rubinius/rubinius#3513]
Consider a main script `main.rb` that autoloads `:Foo` from `foo_extended.rb`. `foo_extended.rb` in turn autoloads `:Foo` from `foo_base.rb` and subsequently reopens the class `Foo` to extend it. In MRI 2.1.7, `main.rb` can see the composite class `Foo`, but in rbx 2.5.8, `main.rb` can only see the definition of `Foo` from `foo_extended.rb`; the base class is neither loaded nor extended. 
- Doing `Foo.class_eval` in `foo_extended.rb` instead of `class Foo` does not affect the behavior described above. 
- Subclassing `Foo` in `foo_extended.rb` instead of monkeypatching `Foo` works in both MRI 2.1.7 and rbx 2.5.8. 
- `require`'ing `foo_extended.rb` instead of autoloading it also works in both. 
#### `rbx -v` (built from source using `ruby-build`)

```
rubinius 2.5.8 (2.1.0 bef51ae3 2015-09-28 3.4 JI) [x86_64-linux-gnu]
```
#### `ruby -v` (built from source using `ruby-build`)

```
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]
```
#### `uname -a`

```
Linux aphrodite 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I can't find `config.rb` or `configure.log` but if you can give me a hint where to locate them I will upload them as a Gist. 

```
mwp@aphrodite:~/.rbenv/versions$ find rbx-2.5.8/ -name config.rb
rbx-2.5.8/gems/gems/i18n-0.7.0/lib/i18n/config.rb
rbx-2.5.8/gems/gems/rubysl-webrick-2.0.0/lib/webrick/config.rb
rbx-2.5.8/gems/gems/rack-1.6.4/lib/rack/config.rb
rbx-2.5.8/gems/gems/http-0.9.8/spec/support/servers/config.rb
rbx-2.5.8/gems/gems/bundler-1.10.6/lib/bundler/cli/config.rb
rbx-2.5.8/gems/gems/bundler-1.10.5/lib/bundler/cli/config.rb
rbx-2.5.8/gems/gems/rubysl-openssl-2.3.0/lib/openssl/config.rb
rbx-2.5.8/gems/gems/rubysl-xmlrpc-2.0.0/lib/xmlrpc/config.rb
mwp@aphrodite:~/.rbenv/versions$ find rbx-2.5.8/ -name configure.log
mwp@aphrodite:~/.rbenv/versions$
```

**Comment by YorickPeterse** [comment]
Can you provide said sample scripts so we can try this out?

**Comment by mwpastore** [comment]
Sure thing.

```ruby
# main.rb

# Case 1: Works in MRI 2.1.7 but not in RBX 2.5.8.
autoload :Foo, './foo_extended'
Foo.new.bar

# Case 2: Works in MRI 2.1.7 and in RBX 2.5.8.
#autoload :FooBar, './foo_extended'
#FooBar.new.bar

# Case 3: Works in MRI 2.1.7 and in RBX 2.5.8.
#require_relative 'foo_extended'
#Foo.new.bar
```

```ruby
# foo_extended.rb

autoload :Foo, './foo_base'

# Case 1(A): Works in MRI 2.1.7 but not in RBX 2.5.8.
class Foo
end

# Case 1(B): Works in MRI 2.1.7 but not in RBX 2.5.8.
#Foo.class_eval do
#end

# Case 2: Works in MRI 2.1.7 and in RBX 2.5.8.
#class FooBar < Foo
#end
```

```ruby
# foo_base.rb

puts 'Base class loaded!'

class Foo
  def bar
    puts 'Hello, world!'
  end
end
```

**Comment by YorickPeterse** [comment]
Confirmed this fails (as of 4eec62a0) with:

```
An exception occurred running main.rb

undefined method `bar' on an instance of Foo. (NoMethodError)

Backtrace:

  Kernel(Foo)#bar (method_missing) at kernel/delta/kernel.rb:78
                 Object#__script__ at main.rb:2
  Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
  Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
           Rubinius::Loader#script at kernel/loader.rb:656
             Rubinius::Loader#main at kernel/loader.rb:842
```

**Comment by brixen** [comment]
Here's the MRI ticket https://bugs.ruby-lang.org/issues/11570

Here's how I see this:

1. the main.rb script begins to run, defining an Autoload for `:Foo`
2. the code `Foo.new.bar` executes, with the first step being, essentially, `const_get :Foo`
3. the Autoload on `:Foo` triggers, which starts loading foo_extended.rb
4. in foo_extended.rb, another Autoload is defined for `:Foo`
5. then `class Foo` executes.

My position would be that the mention of `Foo` in step 5 _shouldn't_ trigger an autoload because the purpose of `class Foo` is to define Foo. We'll see what MRI says.
