### ISSUE TITLE
Open3 methods not working in 1.9

### ISSUE THREAD

**Issue by cldwalker** [rubinius/rubinius#1609]
Seems they all call Open3.popen_run which calls Kernel#spawn which isn't defined yet. Example:

``` ruby
$ irb -ropen3
>> ar = Open3.popen3('ls')
NoMethodError: undefined method `spawn' on Open3 (Module)
    kernel/delta/kernel.rb:81:in `spawn (method_missing)'
    /Users/me/Developer/.rbenv/versions/rbx-2.0.0-dev/lib/19/open3.rb:202:in `popen_run'
    /Users/me/Developer/.rbenv/versions/rbx-2.0.0-dev/lib/19/open3.rb:90:in `popen3'
```
