### ISSUE TITLE
2.2.10 fails to build on MacOS 10.10.5

### ISSUE THREAD

**Issue by kognate** [rubinius/rubinius#3532]
When building I get an error about a `this` pointer that cannot be null.  

`error: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true [-Werror,-Wundefined-bool-conversion]`

```
In file included from vm/agent.cpp:22:
In file included from /private/var/folders/_d/mtbcxz4x3b5djbb_5wgnc0z00000gn/T/ruby-build.20151210102940.1699/rubinius-2.2.10/vm/vm.hpp:7:
In file included from /private/var/folders/_d/mtbcxz4x3b5djbb_5wgnc0z00000gn/T/ruby-build.20151210102940.1699/rubinius-2.2.10/vm/globals.hpp:28:
In file included from /private/var/folders/_d/mtbcxz4x3b5djbb_5wgnc0z00000gn/T/ruby-build.20151210102940.1699/rubinius-2.2.10/vm/gc/root.hpp:8:
/private/var/folders/_d/mtbcxz4x3b5djbb_5wgnc0z00000gn/T/ruby-build.20151210102940.1699/rubinius-2.2.10/vm/oop.hpp:612:14: error: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true [-Werror,-Wundefined-bool-conversion]
      assert(this && (!reference_p() || (type_id() > InvalidType && type_id() < LastObjectType)));
             ^~~~ ~~
```

Removing the `this` allows the build to complete and tests run.  

c++ is 

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

This error showed up in both `rbenv install` and source install.    I've patched it and can submit a PR if
desired.

**Comment by jc00ke** [comment]
Do you get any errors when building from source? That version is super old.

**Comment by YorickPeterse** [comment]
Please upgrade to the latest version, said problem has been fixed since v2.6 (50aa7356e3c750fadb6665508e66d2f6923c7529).
