### ISSUE TITLE
nokogiri 1.5.0 doesn't work with rubinius 1.2.3

### ISSUE THREAD

**Issue by jeremyevans** [rubinius/rubinius#1061]
```
nokogiri.c:41: error: static declaration of 'ruby_strdup' follows non-static declaration
/usr/local/lib/rubinius/include/ruby.h:1736: error: previous declaration of 'ruby_strdup' was here
```

IMO, it's a bug in nokogiri and not rubinius, but evan asked that I open it here.
