### ISSUE TITLE
undef :type via open classes after class is defined throws "undefined method type"

### ISSUE THREAD

**Issue by freeformz** [rubinius/rubinius#469]
<pre>
  rbx-1.0.1-head > module Test
  rbx-1.0.1-head ?>  class Foo; end
  rbx-1.0.1-head ?>  end
   => nil 
  rbx-1.0.1-head > module Test
  rbx-1.0.1-head ?>  class Foo
  rbx-1.0.1-head ?>    undef :type
  rbx-1.0.1-head ?>    end
  rbx-1.0.1-head ?>  end
  NameError: undefined method `type' for Test::Foo
     from Module(Class)#instance_method at kernel/common/module.rb:266
     from { } in Module(Class)#undef_method at kernel/common/module.rb:169
     from Array#each at kernel/bootstrap/array.rb:66
     from Module(Class)#undef_method at kernel/common/module.rb:166
     from Rubinius::StaticScope#__undef_method__ at kernel/common/static_scope.rb:82
     from Test::Foo.__class_init__ (Foo) at (irb):6
     from Test.__module_init__ (Test) at (irb):5
     from { } in Object#irb_binding at (irb):4
  rbx-1.0.1-head >
</pre>

<pre>
$ rbx --version
rubinius 1.0.1 (1.8.7 7d840291 2010-06-03 JI) [x86_64-apple-darwin10.4.0]
</pre>

This also happens in stock rbx-1.0.1

Works in MRI 1.8.7-p174 (and AFAIK all others)

<pre>
$ irb
 > module Test
 ?>  class Foo; end
 ?>  end
 => nil 
 > module Test
 ?>  class Foo
 ?>    undef :type
 ?>    end
 ?>  end
 => nil 
 > 
</pre>
