### ISSUE TITLE
2.4.1 Fails to build on CentOS 6.4

### ISSUE THREAD

**Issue by aaronjwhiteside** [rubinius/rubinius#3235]
4: CXX vm/ontology.cpp
5: CXX vm/oop.cpp
5: CXX vm/park.cpp
5: CXX vm/shared_state.cpp
4: CXX vm/signal.cpp
4: CXX vm/stack_variables.cpp
5: CXX vm/state.cpp
5: CXX vm/symbol_table.cpp
4: CXX vm/type_info.cpp
5: CXX vm/unwind_info.cpp
5: CXX vm/util/file.cpp
5: CXX vm/util/logger.cpp
cc1plus: warnings being treated as errors
vm/util/logger.cpp: In member function ‘void rubinius::utilities::logger::FileLogger::write_log(const char_, const char_, int)’:
vm/util/logger.cpp:286: error: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result
vm/util/logger.cpp:287: error: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result
vm/util/logger.cpp:288: error: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result
vm/util/logger.cpp:289: error: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result
vm/util/logger.cpp:290: error: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result
At global scope:
cc1plus: error: unrecognized command line option "-Wno-unused-result"
cc1plus: error: unrecognized command line option "-Wno-unused-result"
Error: g++ -I/usr/local/src/rubinius-2.4.1/vm -I/usr/local/src/rubinius-2.4.1/vm/include -I/usr/local/src/rubinius-2.4.1/vm/builtin -I. -Ivm/test/cxxtest -I/usr/local/src/rubinius-2.4.1/vendor/udis86 -I/usr/local/src/rubinius-2.4.1/vendor/libffi/include -Ivendor/double-conversion/src -DHAVE_CONFIG_H -I/usr/local/src/rubinius-2.4.1/vm/include/capi -I/usr/local/src/rubinius-2.4.1/vendor/oniguruma -I/usr/local/src/rubinius-2.4.1/vendor/libtommath -pipe -Wall -fno-omit-frame-pointer -g  -Wno-unused-result -fPIC  -O2 -DHAS_EXECINFO -DHAVE_SPT_REUSEARGV -DHAVE_CLOCK_GETTIME -DHAVE_NL_LANGINFO -DHAVE_POSIX_FADVISE -DHAVE_STRNLEN -DHAVE_TIMERFD -DHAVE_INOTIFY -DHAVE_TM_GMTOFF -DHAVE_TM_ZONE -DHAVE_TIMEZONE -DHAVE_TZNAME -DHAVE_DAYLIGHT -DHAVE_ALLOCA_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TIMES_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_STDARG_H -DSTRERROR_R_CHAR_P -I/usr/include -I/usr/include -D_GNU_SOURCE -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -DENABLE_LLVM -Wno-unused-function -Werror -DRBX_PROFILER -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-rtti -fvisibility-inlines-hidden  -Wno-unused-result    -c -o vm/util/artifacts/logger.cpp.o vm/util/logger.cpp
3: CXX vm/util/murmur_hash3.cpp
3: CC vm/util/random.c
3: CC vm/util/sha1.c
3: CC vm/util/siphash.c
3: CXX vm/util/spinlock.cpp
3: CC vm/util/strftime.c
3: CC vm/util/time64.c
3: CXX vm/util/timer.cpp
3: CC vm/util/timing.c
3: CC vm/util/utf8.c
3: CC vm/util/vsnprintf.c
3: CXX vm/vm.cpp
3: CXX vm/vm_thread_state.cpp
In file included from vm/type_info.cpp:98:
vm/gen/typechecks.gen.cpp: In static member function ‘static void rubinius::TypeInfo::auto_learn_fields(rubinius::State_)’:
vm/gen/typechecks.gen.cpp:637: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
rake aborted!
Error compiling
/usr/local/src/rubinius-2.4.1/vendor/gems/gems/daedalus-core-0.1.0/lib/daedalus.rb:68:in `command'
/usr/local/src/rubinius-2.4.1/vendor/gems/gems/daedalus-core-0.1.0/lib/daedalus.rb:234:in`cxx_compile'
/usr/local/src/rubinius-2.4.1/vendor/gems/gems/daedalus-core-0.1.0/lib/daedalus.rb:221:in `compile'
/usr/local/src/rubinius-2.4.1/vendor/gems/gems/daedalus-core-0.1.0/lib/daedalus.rb:433:in`build'
/usr/local/src/rubinius-2.4.1/vendor/gems/gems/daedalus-core-0.1.0/lib/daedalus.rb:895:in `block (2 levels) in perform_tasks'
Tasks: TOP => build => build:build => vm/vm
(See full trace by running task with --trace)
!!! Compiling rbx 2.4.1 failed!
